[package]
name = "relis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.2.0"
glob = "0.3.1"
polars = "0.27.2"
regex = "1.7.1"
